### ISSUE TITLE
Bug: login page submit button does nothing

### ISSUE THREAD

**Issue by thomaskise** [gig-central/gig-repo-1#175] opened 2019-05-23 08:47 UTC
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Bug
###_Severity (1-4; 1 - not severe, 4 - very severe):
 2
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
2
###_Synopsis - describe bug/task/future request, in more detail: 
Submit button doesn't work. Click on it, and nothing happens.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Click on the button and get logged in

###_Actual Behavior - what the behavior is instead, for bugs only: 
Click on the button and nothing happens

###_Steps to Repro the Issue, for bugs only:
Enter credentials
Click on button

###_Other Notes, for bug/task/future requests: 
This was working earlier this week.

**Comment by hvncodes** [comment] 2019-05-23 09:24
I'll look into this.

**Comment by hvncodes** [comment] 2019-05-23 10:06
I was able to fix the button and have it do something when clicked on. Now the problem is having it send the entered credentials somewhere to check if the user can be logged in or not.

**Comment by craigbpeterson** [comment] 2019-05-24 18:31
This bug has been resolved by the following pull request:
https://github.com/gig-central/gig-repo-1/pull/176

**Closed** 2019-05-24 18:32 UTC
Labels: bug
